from ParseNaMDLog import ParseNaMDLog
import os
import sys

class Energy:
    """ Class doc """
    
    def __init__ (self):
        """ Class initialiser """
        pass

    def energy(self, log = False):
        """ Function doc """
        if  ff_type == 'charmm':
            write_NaMD_input_file (molecule = self, Type='energy')
            os.system('namd2 SinglePoint.namd > SinglePoint.log')
            energy = ParseNaMDLog('SinglePoint.log', log=log)
            return energy


def write_NaMD_input_file(molecule=None, Type='energy', parameters = None):
    """ Function doc """
    text = ''
    if molecule._type == 'charmm':

        coordinates = 'SinglePoint.pdb'
        structure = molecule.psf
        parameters = molecule.param
        paratypecharmm = 'on'

        text += '# NAMD Config file - autogenerated by NAMDgui plugin\n'
        text += '# Author: Jan Saam,  saam@charite.de                \n'
        text += '# input                                             \n'
        text += 'coordinates             ' + coordinates + '\n'
        text += 'structure               ' + structure + '\n'
        text += 'parameters              ' + parameters + '\n'
        text += 'paratypecharmm          ' + paratypecharmm + '\n\n'

        text += '# output                                                                 \n'
        text += 'set output              tmp                                              \n'
        text += 'outputname              $output                                          \n'
        text += 'dcdfile                 ${output}.dcd                                    \n'
        text += 'xstFile                 ${output}.xst                                    \n'
        text += 'dcdfreq                 50                                               \n'
        text += 'xstFreq                 50                                               \n'
        text += '                                                                         \n'
        text += 'binaryoutput            no                                               \n'
        text += 'binaryrestart           no                                               \n'
        text += 'outputEnergies          100                                              \n'
        text += 'restartfreq             1000                                             \n'
        text += '                                                                         \n'
        text += 'fixedAtoms              off                                              \n'
        text += '                                                                         \n'
        text += '# Basic dynamics                                                         \n'
        text += 'exclude                 scaled1-4                                        \n'
        text += '1-4scaling              1                                                \n'
        text += 'COMmotion               no                                               \n'
        text += 'dielectric              1.0                                              \n'
        text += '                                                                         \n'
        text += '# Simulation space partitioning                                          \n'
        text += 'switching               on                                               \n'
        text += 'switchdist              9                                                \n'
        text += 'cutoff                  10                                               \n'
        text += 'pairlistdist            12                                               \n'
        text += '                                                                         \n'
        text += '# Multiple timestepping                                                  \n'
        text += 'firsttimestep           0                                                \n'
        text += 'timestep                1                                                \n'
        text += 'stepspercycle           20                                               \n'
        text += 'nonbondedFreq           2                                                \n'
        text += 'fullElectFrequency      4                                                \n'
        text += '                                                                         \n'
        text += '# Temperature control                                                    \n'
        text += '                                                                         \n'
        text += 'set temperature         298                                              \n'
        text += 'temperature             $temperature;  # initial temperature             \n'
        text += '                                                                         \n'
        text += '                                                                         \n'
        text += 'GBIS                    on                                               \n'
        text += 'SASA                    on                                               \n'
        text += '# Scripting                                                              \n'
        
        if _type == 'energy':
            text += 'run 0                                                                    \n'
            output_file = open('SinglePoint.namd', "w")
            output_file.write(text)
            output_file.close()
        
        if _type == 'minimize':
            text += 'minimize 100                                                             \n'
            output_file = open('Minimize.namd', "w")
            output_file.write(text)
            output_file.close()
            
        #if _type == 'dynamics':
        #text += 'minimize 100                                                             \n'    
       #text += 'minimize            1000                                                 \n'

    #output_file = open('SinglePoint.namd', "w")
    #output_file.write(text)
    #output_file.close()
